#!/bin/bash
result=$(find $DIR_TOP -name "in.*" -not -path "$DIR_TOP/.git/*")
for file in $result
do
  my_dirname=$(dirname $file)/
  my_basename=$(basename $file)
  my_filename=${my_basename:3}
  rm -f "${my_dirname}${my_filename}"
done
