BUILD_SRC   := $(wildcard *.c)
BUILD_OUT   := $(DIR_TEST_OUT)
BUILD_FLAGS := -Wno-unused-parameter \
							 -Og -g3
BUILD_LIBS  := -lm -ldl
BUILD_EXE   := 1
BUILD_USE   := 1

include $(DIR_TOP)/Rules.make
