BUILD_TYPE  := $(BUILD_EXE)
BUILD_FLAGS  = -D__RANDOM__=$$RANDOM
BUILD_INCL  := $(DIR_TOP)/tests/preempt
BUILD_LIBS   = $(PROJECT_NAME)
BUILD_USE    = 1
BUILD_LANG   = cpp

include $(DIR_TOP)/Rules.make
